# © 2021 DrewCrawfordApps LLC.
# Unless explicitly acquired and licensed from Licensor under another
# license, the contents of this file are subject to the Reciprocal Public
# License ("RPL") Version 1.5, or subsequent versions as allowed by the RPL,
# and You may not copy or use this file in either source code or executable
# form, except in compliance with the terms and conditions of the RPL.
# 
# All software distributed under the RPL is provided strictly on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND
# LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
# LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific
# language governing rights and limitations under the RPL. 
- name: reconfigure
  block:
      - name: "Remove existing service"
        command:
          chdir: "~/github-actions-runner"
          cmd: "./svc.sh uninstall"
        when: installed
      - name: "Remove existing runner"
        command:
          chdir: "~/github-actions-runner"
          cmd: "./config.sh remove --token {{ runner_token }}"
        when: has_configuration == true
      - name: Combine labels
        set_fact:
          labels: "{{ labels|default([]) + programmatic_labels|default([]) }}"
      - name: Configure
        command:
          
          chdir: "~/github-actions-runner"
          cmd: "./config.sh --url {{ runner_url }} --token {{ runner_token }} --replace --labels {{ labels|join(',') }} --unattended"
        notify: start or restart
        environment: 
          PATH: /Users/drew/.gem/ruby/2.6.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/git/bin